### PR TITLE
Official docker images.

### PR DESCRIPTION
**Pull request by fancycode**

### CODE REVIEW

**Comment by alexanderadam** [comment]
This looks perfect to me :star_struck:

**Comment by fancycode** [comment]
> This looks perfect to me star_struck

Thanks, first images are avaliable here https://hub.docker.com/r/strukturag/nextcloud-spreed-signaling

**Comment by jakobroehrl** [comment]
Thanks a lot. @fancycode 
Do I still need Janus, Nuts, nginx? Or is all of it packed into the docker file?

**Comment by fancycode** [comment]
Our packages only provide the signaling server / -proxy. You will need to run the other services (either manually or from other images), so they can be used by this ones.

**Pull request merged**
