### PR TITLE
Update Dockerfile versions

### PR DESCRIPTION
**Pull request by solracsf**
Running these without issues ATM.

### CODE REVIEW

**Comment by fancycode** [comment]
Thanks! I added CI for the additional `Dockerfile` in #258, could you please rebase your PR on `master`.

**Comment by solracsf** [comment]
Hey @fancycode do you mind to add this workflow to this repo? Thanks :)

https://github.com/nextcloud/server/blob/master/.github/workflows/command-rebase.yml

**Comment by fancycode** [comment]
> Hey @fancycode do you mind to add this workflow to this repo? Thanks :)
> 
> https://github.com/nextcloud/server/blob/master/.github/workflows/command-rebase.yml

Don't I also need a bot that handles the comments for this workflow? Where can I get that from?

**Comment by solracsf** [comment]
Hum.
Maybe https://docs.github.com/en/actions/using-workflows/using-starter-workflows#using-starter-workflows (see step 6)?

**Comment by fancycode** [comment]
> Hum. Maybe https://docs.github.com/en/actions/using-workflows/using-starter-workflows#using-starter-workflows (see step 6)?

Yeah, I know about secrets in workflow but wasn't sure about the value of this one. I now assume it's an access token of the user to perform the actions. PR is in #260 - let's see...

**Comment by fancycode** [comment]
> [...] PR is in #260 - let's see...

Seems to be working now :tada: Thanks for the suggestion!

**Comment by solracsf** [comment]
More easy to rebase any PR at any time ;)

**Pull request merged**
