### PR TITLE
docker: Don't rely on default values when updating TURN settings.

### PR DESCRIPTION
**Pull request by fancycode**
Replaces #432

@3x3cut0r Please test, this is better than your change as it won't replace other `secret`  values in the config files.

### CODE REVIEW

**Comment by fancycode** [comment]
> i cannot test it atm but looking at the code ... why do you escape and insert the \? in the search pattern?: `#\?apikey` `#\?secret`

This is so both `apikey = foo`  and `#apikey = foo`  get updated. Same for the TURN `secret`.

**Comment by 3x3cut0r** [comment]
i understand the '?' inside the sed command and i know what you are trying to do, but is the backslach '\' infront of the questionmark not escaping this function of 'the char before is optional' to a simple character '?' ?

**Comment by fancycode** [comment]
Sed requires "zero-or-no-matches" to be written as `\?`:
https://www.gnu.org/software/sed/manual/html_node/Regular-Expressions.html

**Comment by 3x3cut0r** [comment]
interesting ... i never ever did it like this.
then i should be fine!
then maybe it should also be done like this on the other vars, no?

**Pull request merged**
