### PR TITLE
Support toggling audio/video in subscribed streams.

### PR DESCRIPTION
**Pull request by fancycode**
Follow-up to #191 

The command `selectStream` also supports optional boolean flags `audio` and `video` that can be used to enable/disable receiving the corresponding media from the stream. The parameters of `selectStream` can also be included in the payload of `requestoffer` for example to subscribe a stream with video initially disabled.

The new flags are similar to the existing `substream` / `temporal`.

@danxuliu please review, is this something you could work with?

### CODE REVIEW

**Comment by fancycode** [comment]
I updated the PR to also support `audio` / `video` in `update` requests.

From reading the code of Janus, they should also be evaluated with `update: true`. In your tests with Talk master: did you change something that the new flags are included in the `requestoffer`? At least I couldn't find them being included.

**Comment by danxuliu** [comment]
> From reading the code of Janus, they should also be evaluated with `update: true`. In your tests with Talk master: did you change something that the new flags are included in the `requestoffer`? At least I couldn't find them being included.

Yes, I added a `payload` object to [`data` in `requestOffer`](https://github.com/nextcloud/spreed/blob/48a74da64eac1a593116694f8c6ca299058f6304/src/utils/signaling.js#L1313), although I did not push the code as it was just for testing.

Nevertheless, I also added `configure_msg["video"] = false` before [`configure_response, err := handle.Message(ctx, configure_msg, nil)`](https://github.com/strukturag/nextcloud-spreed-signaling/blob/86bad15337650ca45dfdaad85a3e5686283868d3/mcu_janus.go#L1259), which from what I understand should block the video when requesting an updated offer, yet the received video was still active after the renegotiation.

**Comment by danxuliu** [comment]
> > From reading the code of Janus, they should also be evaluated with `update: true`.
> 
> Checked the Janus code again and found the issue: [meetecho/janus-gateway#2963](https://github.com/meetecho/janus-gateway/pull/2963)

Nice catch! :-D

If I understand it correctly your fix solves both issues, right? I mean:
- send configure request with `video: false`, then send configure request with `update: true` -> video will be still disabled in the subscriber after the update
- send configure request with `update: true` and `video: false` -> video will be now disabled in the subscriber after the update

**Comment by fancycode** [comment]
I only tested the second part and this was fixed. Didn't test the first scenario yet but assume this will be fixed, too.

**Pull request merged**
