### PR TITLE
Fetch capabilities to check if "v3" signaling API of Talk should be used.

### PR DESCRIPTION
**Pull request by fancycode**
Implements #117 

CC @nickvergessen

### CODE REVIEW

**Review by nickvergessen — APPROVED** [review]
Looks good 🐘

**Comment by fancycode** [comment]
The signaling server is only using `/api/v1/signaling/backend` (without this PR). So you mean I should change this PR to check for `signaling-v3` instead of `conversation-v4` and then switch to `/api/v3/signaling/backend` if it is present?

**Comment by fancycode** [comment]
@nickvergessen Updated to check for `signaling-v3` in the latest commit.

**Review by nickvergessen — APPROVED** [review]

**Comment by fancycode** [comment]
Thanks, squashed.

**Pull request merged**
