### PR TITLE
Expose backend session limits through prometheus stats.

### LINKED ISSUE #787: Add sessionlimit to prometheus export
I think it would be useful to have the value of sessionlimit present in the Prometheus export.

Both the global value and the backend-specific values should be there. This would help in monitoring usage by backends and put in place an alerting system.

While these values can also be obtained with parsing the configuration file and/or the etcd database, to have them in the Prometheus export would make the process simpler.

### PR DESCRIPTION
**Pull request by fancycode**
Resolves #787 

@pmarini-nc FYI, don't know if you have the possibility to test this from source

### CODE REVIEW

**Comment by pmarini-nc** [comment]
@fancycode , just tested it and it works fine. Thanks a lot!
Only thing maybe it is worth adding the global limit as well?

**Comment by fancycode** [comment]
> Only thing maybe it is worth adding the global limit as well?

Not sure what you mean with "global limit". If the signaling server is running with compatibility settings (i.e. not with explicit backend definitions), the session limit will be available in the `compat` backend through the stats.

**Comment by pmarini-nc** [comment]
Hello,

My understanding until now was the following: if a backend defines it, it gets its value of `sessionlimit`. If not it gets the value of a global sessionlimit, as defined in section  [backend].

However this seems not the case, that is: there is no fallback `sessionlimit` (like there is one for `secret`). If so, when we don't specify a sessionlimit in the backend, there is no limit, correct?

**Comment by fancycode** [comment]
> However this seems not the case, that is: there is no fallback `sessionlimit` (like there is one for `secret`). If so, when we don't specify a `sessionlimit` in the backend, there is no limit, correct?

Right, adding a global sessionlimit as fallback for backends that have none defined is tracked in #796

**Pull request merged**
