### PR TITLE
Combine ping requests of different rooms on the same backend.

### PR DESCRIPTION
**Pull request by fancycode**
- [x] Add tests

Requires https://github.com/nextcloud/spreed/pull/7338

Implements #246

### CODE REVIEW

**Comment by fancycode** [comment]
@nickvergessen FYI

**Comment by nickvergessen** [comment]
- [ ] Add feature flag header so the Nextcloud part can show a "upgrade needed" error

**Comment by fancycode** [comment]
> * [x]  Add feature flag header so the Nextcloud part can show a "upgrade needed" error

Added as `multiroom-pings`.

**Comment by fancycode** [comment]
@nickvergessen this is ready for testing against your Talk changes

**Review by nickvergessen — APPROVED** [review]
Works, only need to adjust the log on our side:
`Pinged 2 sessions in room   `

Also set the value to 1 session per request to test the chunking:
```
│[debug] 2022-05-17T18:18:59.000 spreed-hpb       Pinged 1 sessions in room N/A                                                                                         
│[debug] 2022-05-17T18:18:59.000 spreed-hpb       Pinged 1 sessions in room N/A                                                                                         
│[debug] 2022-05-17T18:19:09.000 spreed-hpb       Pinged 1 sessions in room N/A                                                                                        
│[debug] 2022-05-17T18:19:09.000 spreed-hpb       Pinged 1 sessions in room N/A    
```

So works greatly

**Comment by nickvergessen** [comment]
But while thinking on the deployment order, we can both release the update immediately, right?
On our side we lessen the strictness and publish a capability and you only do the multi request when it is there.
So we don't need to tell people to update on Nextcloud.

So we could even backport it on our side and if people update the HPB, they would automatically benefit from the change right away?

**Comment by fancycode** [comment]
> But while thinking on the deployment order, we can both release the update immediately, right? On our side we lessen the strictness and publish a capability and you only do the multi request when it is there. So we don't need to tell people to update on Nextcloud.
> 
> So we could even backport it on our side and if people update the HPB, they would automatically benefit from the change right away?

I think we could release independently: the old signaling server will work as before and still work with the changes in Talk. With this PR merged, the batched pings will only be sent if the `session-ping-limit` value is there (i.e. with a new version of Talk). The old server with a new version of Talk will also work as before.
There is no need for a capability, the check for `session-ping-limit` should be sufficient.

**Comment by fancycode** [comment]
> If you want to have a shorter list you could remove it again as we don't seem to need it.

Ah right, true.

**Pull request merged**
