### PR TITLE
Add special events to update "incall" flags of all sessions.

### PR DESCRIPTION
**Pull request by fancycode**
Implements #203

CC @nickvergessen

### CODE REVIEW

**Comment by nickvergessen** [comment]
```json
{"type":"event","event":{"target":"participants","type":"update","update":{"roomid":"5439271893","incall":0,"all":true}}}
```

Event arrived as expected :)

**Comment by fancycode** [comment]
> Web UI patch of talk included in [nextcloud/spreed#6948](https://github.com/nextcloud/spreed/pull/6948) now, works greatly

Nice :rocket: Do you need a feature flag to detect this functionality?

**Comment by fancycode** [comment]
> We will just declare all others incompatible again, yes please.

Feature `incall-all` added here:
https://github.com/strukturag/nextcloud-spreed-signaling/pull/208/files#diff-af77f900ef416cef30db02dfd2da71ca4d6710fdc20cbb757283146a3b173f52R341

**Comment by nickvergessen** [comment]
🚀  thanks a lot

**Comment by nickvergessen** [comment]
Just to avoid confusion, this is not yet available in the repository, right?

**Comment by nickvergessen** [comment]
Okay, no pressure was just confused as I was retesting my branch and it showed me the update warning :D

**Pull request merged**
